@startuml "Sistema RutaFlex"

left to right direction

skinparam usecase {
  BackgroundColor #FFF9C4
  BorderColor #7A1631
  StereotypeFontColor #2E7D32
}

skinparam actor {
  BackgroundColor #FFF9C4
  BorderColor #7A1631
  StereotypeFontColor #2E7D32
}

skinparam Arrow {
  Color #7A1631
}

actor "Estudiante Pasajero" as Passenger
actor "Estudiante Conductor" as Driver
actor "Administrador" as Admin

actor "Servicio de Correo\nInstitucional" as EmailService
actor "Servicio de\nMapas" as MapsService

rectangle "Sistema RutaFlex" {

  usecase "Iniciar Sesión" as UC1

  usecase "Gestionar Perfil" as UC2

  usecase "Buscar Viajes" as UC3

  usecase "Publicar Ruta" as UC4

  usecase "Gestionar Viajes" as UC5

  usecase "Enviar Mensajes" as UC6

  usecase "Calificar Usuario" as UC7

  usecase "Consultar Historial" as UC8

  usecase "Consultar Ahorro" as UC9

  usecase "Gestionar Usuarios" as UC10

}

Passenger -- UC1
Passenger -- UC2
Passenger -- UC3
Passenger -- UC6
Passenger -- UC7
Passenger -- UC8
Passenger -- UC9

Driver -- UC1
Driver -- UC2
Driver -- UC4
Driver -- UC5
Driver -- UC6
Driver -- UC7
Driver -- UC8
Driver -- UC9

Admin -- UC1
Admin -- UC10

UC1 -- EmailService
UC3 -- MapsService
UC4 -- MapsService

@enduml