@startuml ""

package Communication {

    package ChatAggregate {

        class Chat <<AggregateRoot>> {
            - ChatId: id
            - TripId: tripId
        }

        class ChatId <<ValueObject>> {
            - Long: value
        }

        class Message <<Entity>> {
            - MessageId: id
            - UserId: senderId
            - MessageContent: content
        }

        class MessageId <<ValueObject>> {
            - Long: value
        }

        class MessageContent <<ValueObject>> {
            - String: value
        }

        class Notification <<Entity>> {
            - NotificationId: id
            - String: type
        }

        class NotificationId <<ValueObject>> {
            - Long: value
        }
    }
}

package Shared {

    class UserId <<ValueObject>> {
        - Long: value
    }

    class TripId <<ValueObject>> {
        - Long: value
    }

}

Chat --> ChatId
Chat --> TripId

Chat "1" *--> "1..*" Message
Chat "1" *--> "*" Notification

Message --> MessageId
Message --> MessageContent
Message --> UserId

Notification --> NotificationId

@enduml