@startuml ""

package TripManagement {

    package TripAggregate {

        class Trip <<AggregateRoot>> {
            - TripId: id
            - DriverId: driverId
            - Route: route
        }

        class TripId <<ValueObject>> {
            - Long: value
        }

        class DriverId <<ValueObject>> {
            - Long: value
        }

        class Route <<Entity>> {
            - RouteId: id
            - Location: origin
            - Location: destination
            - DateTime: departureTime
        }

        class RouteId <<ValueObject>> {
            - Long: value
        }

        class Location <<ValueObject>> {
            - String: address
        }

        class SeatAvailability <<Entity>> {
            - Integer: availableSeats
        }
    }
}

package Shared {

    class UserId <<ValueObject>> {
        - Long: value
    }

}

Trip --> TripId
Trip --> DriverId

Trip "1" *--> "1" Route
Trip "1" *--> "1" SeatAvailability

Route --> RouteId
Route --> Location

@enduml