@startuml ""

package UserManagement {

    package UserAggregate {

        class User <<AggregateRoot>> {
            - UserId: id
            - FullName: name
            - InstitutionalEmail: email
            - PhoneNumber: phoneNumber
        }

        class UserId <<ValueObject>> {
            - Long: value
        }

        class FullName <<ValueObject>> {
            - String: firstName
            - String: lastName
        }

        class InstitutionalEmail <<ValueObject>> {
            - String: value
        }

        class PhoneNumber <<ValueObject>> {
            - String: value
        }

        class Profile <<Entity>> {
            - ProfileId: id
            - String: biography
            - String: profilePicture
        }

        class ProfileId <<ValueObject>> {
            - Long: value
        }

        class InstitutionalCredential <<Entity>> {
            - CredentialId: id
            - Boolean: verified
        }

        class CredentialId <<ValueObject>> {
            - Long: value
        }
    }
}

User --> UserId
User --> FullName
User --> InstitutionalEmail
User --> PhoneNumber

User "1" *--> "1" Profile
User "1" *--> "1" InstitutionalCredential

Profile --> ProfileId
InstitutionalCredential --> CredentialId

@enduml