@startuml ""

package HistoryAndReputation {

    package RatingAggregate {

        class Rating <<AggregateRoot>> {
            - RatingId: id
            - RatedUserId: ratedUserId
            - Score: score
        }

        class RatingId <<ValueObject>> {
            - Long: value
        }

        class RatedUserId <<ValueObject>> {
            - Long: value
        }

        class Score <<ValueObject>> {
            - Integer: value
        }
    }

    package TripHistoryAggregate {

        class TripHistory <<AggregateRoot>> {
            - HistoryId: id
            - UserId: userId
        }

        class HistoryId <<ValueObject>> {
            - Long: value
        }

        class TripRecord <<Entity>> {
            - TripRecordId: id
            - TripId: tripId
        }

        class TripRecordId <<ValueObject>> {
            - Long: value
        }

        class Savings <<Entity>> {
            - SavingsId: id
            - Decimal: amount
        }

        class SavingsId <<ValueObject>> {
            - Long: value
        }

        class CO2Savings <<Entity>> {
            - CO2SavingsId: id
            - Decimal: kilograms
        }

        class CO2SavingsId <<ValueObject>> {
            - Long: value
        }
    }
}

package Shared {

    class UserId <<ValueObject>> {
        - Long: value
    }

    class TripId <<ValueObject>> {
        - Long: value
    }

}

Rating --> RatingId
Rating --> RatedUserId
Rating --> Score

TripHistory --> HistoryId
TripHistory --> UserId

TripHistory "1" *--> "*" TripRecord
TripHistory "1" *--> "*" Savings
TripHistory "1" *--> "*" CO2Savings

TripRecord --> TripRecordId
TripRecord --> TripId

Savings --> SavingsId
CO2Savings --> CO2SavingsId

@enduml