@startuml
skinparam classAttributeIconSize 0

title Bounded Context - Seguridad e Historial

class Calificacion {
  +id: idCalificacion
  +puntaje: int
  +comentario: String
  +fecha: DateTime
}

class HistorialViaje {
  +id: idHistorial
  +fechaRegistro: DateTime
  +descripcion: String
}

class Ahorro {
  +id: idAhorro
  +monto: Decimal
  +moneda: String
}

class CO2Ahorrado {
  +id: idCo2
  +valor: Decimal
  +unidad: String
}

class ValidacionIdentidad {
  +id: idValidadcion
  +estado: String
  +fechaValidacion: DateTime
}

HistorialViaje "1" o-- "0..*" Calificacion
HistorialViaje "1" o-- "0..*" Ahorro
HistorialViaje "1" o-- "0..*" CO2Ahorrado
ValidacionIdentidad --> HistorialViaje
@enduml