@startuml "Comunicación - Components"
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Comunicación - Component Diagram

Container(spa, "Single Page Application", "Angular")
ContainerDb(db, "Database", "MySQL")

Container_Boundary(api, "Comunicación API") {

    Component(chatController, "ChatController", "Interface Layer")
    Component(chatApplicationService, "ChatApplicationService", "Application Layer")
    Component(chatAggregate, "ChatAggregate", "Domain Layer")
    Component(messageDomainService, "MessageDomainService", "Domain Layer")
    Component(chatRepository, "ChatRepository", "Infrastructure Layer")
    Component(notificationService, "NotificationService", "Infrastructure Layer")
    Component(sharedKernel, "Shared Kernel", "Shared")

}

Rel(spa, chatController, "HTTP / WebSocket")

Rel(chatController, chatApplicationService, "")

Rel(chatApplicationService, chatAggregate, "")
Rel(chatApplicationService, messageDomainService, "")

Rel(chatAggregate, chatRepository, "")
Rel(messageDomainService, chatRepository, "")

Rel(messageDomainService, notificationService, "")

Rel(chatRepository, db, "CRUD")

Rel(chatApplicationService, sharedKernel, "")
Rel(chatAggregate, sharedKernel, "")
Rel(messageDomainService, sharedKernel, "")
Rel(chatRepository, sharedKernel, "")

@enduml
