@startuml "Gestión de Viajes - Components"
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Gestión de Viajes - Component Diagram

Container(spa, "Single Page Application", "Angular")
ContainerDb(db, "Database", "MySQL")

Container_Boundary(api, "Gestión de Viajes API") {

    Component(tripController, "TripController", "Interface Layer")
    Component(tripApplicationService, "TripApplicationService", "Application Layer")
    Component(tripAggregate, "TripAggregate", "Domain Layer")
    Component(routeDomainService, "RouteDomainService", "Domain Layer")
    Component(tripRepository, "TripRepository", "Infrastructure Layer")
    Component(sharedKernel, "Shared Kernel", "Shared")

}

Rel(spa, tripController, "HTTP")

Rel(tripController, tripApplicationService, "")

Rel(tripApplicationService, tripAggregate, "")
Rel(tripApplicationService, routeDomainService, "")

Rel(tripAggregate, tripRepository, "")
Rel(routeDomainService, tripRepository, "")

Rel(tripRepository, db, "CRUD")

Rel(tripApplicationService, sharedKernel, "")
Rel(tripAggregate, sharedKernel, "")
Rel(routeDomainService, sharedKernel, "")
Rel(tripRepository, sharedKernel, "")

@enduml
