@startuml "Gestión de Usuarios - Components"
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Gestión de Usuarios - Component Diagram

Container(spa, "Single Page Application", "Angular")
ContainerDb(db, "Database", "MySQL")

Container_Boundary(api, "Gestión de Usuarios API") {

    Component(userController, "UserController", "Interface Layer")
    Component(userApplicationService, "UserApplicationService", "Application Layer")
    Component(authenticationService, "AuthenticationService", "Application Layer")
    Component(userAggregate, "UserAggregate", "Domain Layer")
    Component(profileDomainService, "ProfileDomainService", "Domain Layer")
    Component(userRepository, "UserRepository", "Infrastructure Layer")
    Component(sharedKernel, "Shared Kernel", "Shared")

}

Rel(spa, userController, "HTTP")

Rel(userController, userApplicationService, "")
Rel(userController, authenticationService, "")

Rel(userApplicationService, userAggregate, "")
Rel(authenticationService, userAggregate, "")

Rel(userAggregate, profileDomainService, "")

Rel(profileDomainService, userRepository, "")
Rel(authenticationService, userRepository, "")

Rel(userRepository, db, "CRUD")

Rel(userApplicationService, sharedKernel, "")
Rel(authenticationService, sharedKernel, "")
Rel(userAggregate, sharedKernel, "")
Rel(profileDomainService, sharedKernel, "")
Rel(userRepository, sharedKernel, "")

@enduml
