@startuml "Historial y Reputación - Components"
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Historial y Reputación - Component Diagram

Container(spa, "Single Page Application", "Angular")
ContainerDb(db, "Database", "MySQL")

Container_Boundary(api, "Historial y Reputación API") {

    Component(historyController, "HistoryController", "Interface Layer")
    Component(historyApplicationService, "HistoryApplicationService", "Application Layer")
    Component(historyAggregate, "HistoryAggregate", "Domain Layer")
    Component(reputationDomainService, "ReputationDomainService", "Domain Layer")
    Component(historyRepository, "HistoryRepository", "Infrastructure Layer")
    Component(sharedKernel, "Shared Kernel", "Shared")

}

Rel(spa, historyController, "HTTP")

Rel(historyController, historyApplicationService, "")

Rel(historyApplicationService, historyAggregate, "")
Rel(historyApplicationService, reputationDomainService, "")

Rel(historyAggregate, historyRepository, "")
Rel(reputationDomainService, historyRepository, "")

Rel(historyRepository, db, "CRUD")

Rel(historyApplicationService, sharedKernel, "")
Rel(historyAggregate, sharedKernel, "")
Rel(reputationDomainService, sharedKernel, "")
Rel(historyRepository, sharedKernel, "")

@enduml
