@startuml
actor "Estudiante Conductor" as Driver
boundary "App RutaFlex" as App
control "TripController" as TripC
entity "TripService" as TripS
database "RutaFlex DB" as DB

Driver -> App : Iniciar sesión
App -> TripC : login(correo, contraseña)
TripC -> DB : validarUsuario()
DB --> TripC : usuario válido
TripC --> App : acceso concedido

Driver -> App : Publicar ruta
App -> TripC : publishRoute(datosRuta)
TripC -> TripS : createTrip(datosRuta)
TripS -> DB : saveTrip()
DB --> TripS : ruta registrada
TripS --> TripC : confirmación
TripC --> App : mostrar éxito

@enduml